# Semgrep + AppSecAI (only)
name: AppSecAI with Semgrep

permissions:
  contents: read
  id-token: write

on:
  workflow_dispatch:

jobs:
  triageAndRemediation:
    runs-on: ubuntu-latest
    env:
      AUTO_CREATE_PRS: "true"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep
        run: |
          pip install semgrep
          semgrep scan --config auto --verbose --sarif --output semgrep-results.sarif .
      - name: AppSecAI
        uses: AppSecureAI/automation-action@v1
        with:
          file: semgrep-results.sarif
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
